# Generated by Django 5.1.2 on 2024-10-26 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('isbn', models.CharField(max_length=100)),
                ('category', models.IntegerField(choices=[(1, 'Criminal Law'), (2, 'Civil Law'), (3, 'Constitutional Law'), (4, 'Administrative Law'), (5, 'International Law'), (6, 'Tort Law'), (7, 'Contract Law'), (8, 'Property Law'), (9, 'Family Law'), (10, 'Corporate Law'), (11, 'Intellectual Property Law'), (12, 'Environmental Law'), (13, 'Labor Law'), (14, 'Tax Law'), (15, 'Immigration Law'), (16, 'Health Law'), (17, 'Sports Law'), (18, 'Cyber Law'), (19, 'Banking Law'), (20, 'Insurance Law'), (21, 'Maritime Law'), (22, 'Aviation Law'), (23, 'Media Law'), (24, 'Education Law'), (25, 'Elder Law'), (26, 'Entertainment Law'), (27, 'Real Estate Law'), (28, 'Trusts and Estates Law'), (29, 'Bankruptcy Law'), (30, 'Securities Law'), (31, 'Antitrust Law'), (32, 'Military Law'), (33, 'Natural Resources Law'), (34, 'Energy Law'), (35, 'Transportation Law'), (36, 'Food and Drug Law'), (37, 'Human Rights Law'), (38, 'Animal Law'), (39, 'Space Law')])),
            ],
        ),
        migrations.AlterField(
            model_name='blsuser',
            name='user_title',
            field=models.IntegerField(choices=[(1, 'Part I Student'), (2, 'Part II Student'), (3, 'Part III Student'), (4, 'Administrator')], default=1),
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('bookmark_id', models.AutoField(primary_key=True, serialize=False)),
                ('page_number', models.IntegerField()),
                ('comments', models.CharField(max_length=1000)),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.book')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='eBook',
            fields=[
                ('ebook_id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='ebooks/')),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.book')),
            ],
        ),
        migrations.CreateModel(
            name='PhysicalBook',
            fields=[
                ('physical_id', models.AutoField(primary_key=True, serialize=False)),
                ('stock_level', models.IntegerField(default=1)),
                ('shelf_num', models.IntegerField()),
                ('condition', models.IntegerField(choices=[(1, 'New'), (2, 'Good'), (3, 'Fair'), (4, 'Poor')])),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.book')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('loan_id', models.AutoField(primary_key=True, serialize=False)),
                ('duration', models.IntegerField(default=7)),
                ('renewed', models.BooleanField(default=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.physicalbook')),
            ],
        ),
        migrations.CreateModel(
            name='Damages',
            fields=[
                ('comments', models.CharField(max_length=1000)),
                ('liabile', models.BooleanField(default=False)),
                ('penalty_issued', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('resolved', models.BooleanField(default=False)),
                ('damage_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('physicalbook_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.physicalbook')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('comments', models.CharField(max_length=1000)),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.book')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
