# Generated by Django 5.1.2 on 2024-10-27 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_book_alter_blsuser_user_title_bookmark_ebook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blsuser',
            name='read_books',
            field=models.ManyToManyField(blank=True, related_name='read_books', to='core.book'),
        ),
        migrations.AddField(
            model_name='ebook',
            name='name',
            field=models.CharField(default='eBookDefault', max_length=100),
        ),
        migrations.AddField(
            model_name='physicalbook',
            name='name',
            field=models.CharField(default='PhysicalBookDefault', max_length=100),
        ),
    ]
