# Generated by Django 5.1.2 on 2024-10-27 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_blsuser_read_books_ebook_name_physicalbook_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='physicalbook',
            name='book_id',
        ),
        migrations.AlterField(
            model_name='loan',
            name='book_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.book'),
        ),
        migrations.AlterField(
            model_name='damages',
            name='physicalbook_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.book'),
        ),
        migrations.AddField(
            model_name='book',
            name='condition',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='book',
            name='ebook',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='book',
            name='file',
            field=models.FileField(blank=True, upload_to='books/'),
        ),
        migrations.AddField(
            model_name='book',
            name='physical',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='book',
            name='stock_level',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='eBook',
        ),
        migrations.DeleteModel(
            name='PhysicalBook',
        ),
    ]
