# Generated by Django 5.1.2 on 2024-10-27 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_physicalbook_book_id_alter_loan_book_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='damages',
            old_name='physicalbook_id',
            new_name='book_id',
        ),
    ]
