# Generated by Django 5.1.2 on 2024-10-29 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_book_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='in_stock',
            field=models.BooleanField(default=True),
        ),
    ]
