# Generated by Django 5.1.2 on 2024-11-01 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_book_in_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='overdue',
            field=models.BooleanField(default=False),
        ),
    ]
