# Generated by Django 5.1.2 on 2024-11-10 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_loan_overdue'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='custody',
            field=models.BooleanField(default=False),
        ),
    ]
