# Generated by Django 5.1.2 on 2024-11-10 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_loan_custody'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='early_return',
            field=models.BooleanField(default=False),
        ),
    ]
