# Generated by Django 5.1.2 on 2024-11-13 22:20

import core.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_loan_early_return'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='duration',
            field=models.IntegerField(default=7, validators=[django.core.validators.MaxValueValidator(7)]),
        ),
        migrations.AlterField(
            model_name='loan',
            name='end_date',
            field=models.DateField(validators=[core.models.check_future]),
        ),
        migrations.AlterField(
            model_name='loan',
            name='start_date',
            field=models.DateField(validators=[core.models.check_future]),
        ),
        migrations.CreateModel(
            name='LoanIssuanceNotes',
            fields=[
                ('note_id', models.AutoField(primary_key=True, serialize=False)),
                ('issued', models.BooleanField()),
                ('start_date', models.DateField()),
                ('reason', models.CharField(max_length=1000)),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.book')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
