# Generated by Django 5.1.2 on 2024-11-15 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_loan_duration_alter_loan_end_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmark',
            old_name='book_id',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='damages',
            old_name='book_id',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='book_id',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='loanissuancenotes',
            old_name='book_id',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='book_id',
            new_name='book',
        ),
    ]
