# Generated by Django 5.1.2 on 2024-11-15 09:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_book_id_bookmark_book_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanissuancenotes',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
