# Generated by Django 5.1.2 on 2024-11-15 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_loanissuancenotes_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
