# Generated by Django 5.1.2 on 2024-11-15 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_loan_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='issuancenote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.loanissuancenotes'),
        ),
    ]
