# Generated by Django 5.1.2 on 2024-11-15 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_loan_issuancenote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loanissuancenotes',
            old_name='note_id',
            new_name='id',
        ),
    ]
