# Generated by Django 5.1.2 on 2024-12-06 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_book_inventory_alter_loan_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='stock_level',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
