# Generated by Django 5.1.2 on 2024-12-11 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_book_stock_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanissuancenotes',
            name='loan_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.loan'),
        ),
    ]
