# Generated by Django 5.1.2 on 2024-12-14 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_loanissuancenotes_loan_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
