# Generated by Django 5.1.2 on 2024-12-17 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_loan_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='issuancenote',
        ),
    ]
