# Generated by Django 5.1.2 on 2024-12-20 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_book_creation_date_alter_book_updated_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='status',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
