# Generated by Django 5.1.2 on 2024-12-21 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_loan_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='damages',
            name='loan_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.loan'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(blank=True, default='Awaiting Collection.', max_length=100),
        ),
    ]
