# Generated by Django 5.1.2 on 2024-12-21 20:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_damages_loan_id_alter_loan_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Damage',
            fields=[
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('student_comments', models.CharField(max_length=1000)),
                ('liabile', models.BooleanField(default=False)),
                ('penalty_issued', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('resolved', models.BooleanField(default=False)),
                ('damage_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[(1, 'Lost'), (2, 'Torn Pages'), (3, 'Water Damage'), (4, 'Stains'), (5, 'Cover Damage'), (6, 'Binding Damage'), (7, 'Missing Pages'), (8, 'Writing or Markings'), (9, 'Spine Damage'), (10, 'Burn Marks'), (11, 'Other')], max_length=100)),
                ('admin_comments', models.CharField(blank=True, max_length=1000)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.book')),
                ('loan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.loan')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Damages',
        ),
    ]
