# Generated by Django 5.1.2 on 2024-12-21 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_damage_delete_damages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='condition',
            field=models.IntegerField(choices=[(1, 'New'), (2, 'Good'), (3, 'Fair'), (4, 'Poor')], default=1),
        ),
        migrations.AlterField(
            model_name='damage',
            name='category',
            field=models.IntegerField(choices=[(1, 'Lost'), (2, 'Torn Pages'), (3, 'Water Damage'), (4, 'Stains'), (5, 'Cover Damage'), (6, 'Binding Damage'), (7, 'Missing Pages'), (8, 'Writing or Markings'), (9, 'Spine Damage'), (10, 'Burn Marks'), (11, 'Other')], default=1),
        ),
    ]
