# Generated by Django 5.1.2 on 2024-12-22 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_book_condition_alter_damage_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewNote',
            fields=[
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('note_id', models.AutoField(primary_key=True, serialize=False)),
                ('comments', models.CharField(max_length=1000)),
                ('blocked', models.BooleanField(default=False)),
                ('review_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.review')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
