# Generated by Django 5.1.2 on 2024-12-23 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_reviewnote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewnote',
            name='review_id',
        ),
        migrations.AddField(
            model_name='review',
            name='revnote',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to='core.reviewnote'),
            preserve_default=False,
        ),
    ]
