# Generated by Django 5.1.2 on 2024-12-23 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_remove_reviewnote_review_id_review_revnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='see',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='revnote',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.reviewnote'),
        ),
    ]
