# Generated by Django 5.1.2 on 2024-12-23 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_review_see_alter_review_revnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewnote',
            name='book_id',
            field=models.ForeignKey(blank=True, default=8, on_delete=django.db.models.deletion.CASCADE, to='core.book'),
            preserve_default=False,
        ),
    ]
