# Generated by Django 5.1.2 on 2024-12-23 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_reviewnote_book_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewnote',
            name='book_id',
        ),
    ]
