# Generated by Django 5.1.2 on 2024-12-24 19:24

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_remove_reviewnote_book_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Penalty',
            fields=[
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('issuance_date', models.DateField(default=datetime.datetime(2024, 12, 24, 19, 24, 42, 180098))),
                ('paid', models.BooleanField(default=False)),
                ('pay_method', models.IntegerField(choices=[(1, 'Cash'), (2, 'Mobile Money'), (3, 'Bank Transfer'), (4, 'Adjustment'), (5, 'Exemption')], default=1)),
                ('penalty_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField(default=1)),
                ('admin_comments', models.CharField(blank=True, max_length=1000)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.book')),
                ('damage_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.loan')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
