# Generated by Django 5.1.2 on 2024-12-24 19:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_alter_penalty_issuance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penalty',
            name='issuance_date',
            field=models.DateField(default=datetime.datetime(2024, 12, 24, 19, 26, 59, 463091, tzinfo=datetime.timezone.utc)),
        ),
    ]
