# Generated by Django 5.1.2 on 2024-12-24 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_alter_penalty_issuance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penalty',
            name='issuance_date',
            field=models.DateField(),
        ),
    ]
