# Generated by Django 5.1.2 on 2024-12-24 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_alter_damage_book_alter_damage_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penalty',
            name='damage_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.damage'),
        ),
    ]
