# Generated by Django 5.1.2 on 2025-01-12 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_alter_penalty_damage_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='numofpages',
            field=models.IntegerField(blank=True, default=10),
        ),
    ]
