# Generated by Django 5.1.2 on 2025-01-26 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_book_numofpages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='end_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='start_date',
            field=models.DateField(),
        ),
    ]
