# Generated by Django 5.1.2 on 2025-01-27 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_alter_loan_end_date_alter_loan_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='blsuser',
            name='banned',
            field=models.BooleanField(default=False),
        ),
    ]
