# Generated by Django 5.1.2 on 2025-01-29 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_onlinebookread_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='damage',
            name='book',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='book',
        ),
        migrations.RemoveField(
            model_name='loanissuancenotes',
            name='book',
        ),
        migrations.RemoveField(
            model_name='penalty',
            name='book',
        ),
        migrations.CreateModel(
            name='PhysicalBook',
            fields=[
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('physical_id', models.AutoField(primary_key=True, serialize=False)),
                ('condition', models.IntegerField(choices=[(1, 'New'), (2, 'Damaged - Pending Inspection'), (3, 'Damaged - Ready for Loan')], default=1)),
                ('withstudent', models.BooleanField(default=False)),
                ('readyforloan', models.BooleanField(default=False)),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.book')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='damage',
            name='physicalbook',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='core.physicalbook'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loan',
            name='physicalbook',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.physicalbook'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanissuancenotes',
            name='physicalbook',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.physicalbook'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='penalty',
            name='physicalbook',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='core.physicalbook'),
            preserve_default=False,
        ),
    ]
