# Generated by Django 5.1.2 on 2025-01-29 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_remove_book_condition_remove_damage_book_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='book_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.book'),
            preserve_default=False,
        ),
    ]
