# Generated by Django 5.1.2 on 2025-01-29 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_loan_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='inventory',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='stock_level',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='loan',
            name='physicalbook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.physicalbook'),
        ),
    ]
