# Generated by Django 5.1.2 on 2025-01-29 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_alter_book_inventory_alter_book_stock_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanissuancenotes',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.book'),
            preserve_default=False,
        ),
    ]
