# Generated by Django 5.1.2 on 2025-01-29 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_loanissuancenotes_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanissuancenotes',
            name='physicalbook',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.physicalbook'),
        ),
    ]
