# Generated by Django 5.1.2 on 2025-02-02 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_alter_loanissuancenotes_physicalbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
