# Generated by Django 5.1.2 on 2025-02-02 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_book_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='audio',
            field=models.FileField(blank=True, upload_to='audio/'),
        ),
    ]
