# Generated by Django 5.1.2 on 2025-02-02 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_book_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='audio_version',
            field=models.BooleanField(default=False),
        ),
    ]
