# Generated by Django 5.1.2 on 2025-03-12 11:57

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_book_audio_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinebookread',
            name='servedpdf',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='file',
            field=models.FileField(blank=True, upload_to='books/', validators=[django.core.validators.FileExtensionValidator(['pdf'], 'incorrect File Type!')]),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=100, validators=[core.models.check_isbn]),
        ),
        migrations.AlterField(
            model_name='loan',
            name='end_date',
            field=models.DateField(blank=True, validators=[core.models.check_future]),
        ),
        migrations.AlterField(
            model_name='loan',
            name='start_date',
            field=models.DateField(validators=[core.models.check_future]),
        ),
    ]
