# Generated by Django 5.1.2 on 2025-03-12 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_onlinebookread_servedpdf_alter_book_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinebookread',
            name='servedpdf',
            field=models.CharField(max_length=1000),
        ),
    ]
