# Generated by Django 5.1.2 on 2025-03-12 20:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_alter_onlinebookread_servedpdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onlinebookread',
            name='id',
        ),
        migrations.AddField(
            model_name='onlinebookread',
            name='read_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='onlinebookread',
            name='servedpdf',
            field=models.FileField(blank=True, upload_to='servedpdfs/', validators=[django.core.validators.FileExtensionValidator(['pdf'], 'incorrect File Type!')]),
        ),
    ]
