# Generated by Django 5.1.2 on 2025-03-12 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_remove_onlinebookread_id_onlinebookread_read_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onlinebookread',
            name='read_id',
        ),
        migrations.AddField(
            model_name='onlinebookread',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
