# Generated by Django 5.1.2 on 2025-03-18 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_remove_onlinebookread_read_id_onlinebookread_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanissuancenotes',
            name='flag',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
    ]
