# Generated by Django 5.1.2 on 2025-03-22 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_loanissuancenotes_flag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blsuser',
            name='read_books',
        ),
        migrations.RemoveField(
            model_name='blsuser',
            name='user_title',
        ),
    ]
