# Generated by Django 5.1.2 on 2025-04-09 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_remove_blsuser_read_books_remove_blsuser_user_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='penalty',
            name='loan_id',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='core.loan'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='penalty',
            name='damage_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.damage'),
        ),
    ]
