# Generated by Django 5.1.2 on 2025-04-10 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_penalty_loan_id_alter_penalty_damage_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinebookread',
            name='nextbook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nextbook', to='core.book'),
        ),
        migrations.AlterField(
            model_name='onlinebookread',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book', to='core.book'),
        ),
        migrations.CreateModel(
            name='SubsequentBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('from_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_book', to='core.book')),
                ('to_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_book', to='core.book')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
