# Generated by Django 5.1.2 on 2025-04-10 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_onlinebookread_nextbook_alter_onlinebookread_book_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubsequentBook',
        ),
    ]
