# Generated by Django 5.1.2 on 2025-04-11 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_alter_onlinebookread_nextbook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onlinebookread',
            name='nextbook',
        ),
    ]
