# Generated by Django 5.1.2 on 2025-04-11 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_remove_onlinebookread_nextbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinebookread',
            name='nextbook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nextread', to='core.onlinebookread'),
        ),
    ]
