# Generated by Django 5.1.2 on 2025-04-16 11:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_remove_onlinebookread_servedpdf_alter_book_isbn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinebookread',
            name='servedpdf',
            field=models.FileField(blank=True, upload_to='servedpdfs/', validators=[django.core.validators.FileExtensionValidator(['pdf'], 'incorrect File Type!')]),
        ),
        migrations.AlterField(
            model_name='onlinebookread',
            name='category',
            field=models.IntegerField(choices=[(1, 'Administrative Law'), (2, 'Animal Law'), (3, 'Antitrust Law'), (4, 'Aviation Law'), (5, 'Banking Law'), (6, 'Bankruptcy Law'), (7, 'Civil Law'), (8, 'Constitutional Law'), (9, 'Contract Law'), (10, 'Corporate Law'), (11, 'Criminal Law'), (12, 'Cyber Law'), (13, 'Education Law'), (14, 'Elder Law'), (15, 'Energy Law'), (16, 'Entertainment Law'), (17, 'Environmental Law'), (18, 'Family Law'), (19, 'Food and Drug Law'), (20, 'Health Law'), (21, 'Human Rights Law'), (22, 'Immigration Law'), (23, 'Insurance Law'), (24, 'Intellectual Property Law'), (25, 'International Law'), (26, 'Labor Law'), (27, 'Maritime Law'), (28, 'Media Law'), (29, 'Military Law'), (30, 'Natural Resources Law'), (31, 'Property Law'), (32, 'Real Estate Law'), (33, 'Securities Law'), (34, 'Space Law'), (35, 'Sports Law'), (36, 'Tax Law'), (37, 'Tort Law'), (38, 'Transportation Law'), (39, 'Trusts and Estates Law')]),
        ),
    ]
