# Generated by Django 5.1.2 on 2025-04-17 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_onlinebookread_servedpdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='penalty',
            name='reason_overdue',
            field=models.BooleanField(default=False),
        ),
    ]
