# Generated by Django 5.1.2 on 2025-04-18 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_penalty_reason_overdue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penalty',
            name='damage_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.damage'),
        ),
        migrations.AlterField(
            model_name='penalty',
            name='loan_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.loan'),
        ),
    ]
