# Generated by Django 5.1.2 on 2025-04-19 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_alter_penalty_damage_id_alter_penalty_loan_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='in_stock',
            field=models.BooleanField(default=False),
        ),
    ]
