# Generated by Django 5.1.2 on 2025-04-19 13:20

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_alter_book_in_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=100, validators=[core.validators.check_not_empty]),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=100, validators=[core.validators.check_not_empty]),
        ),
    ]
