# Generated by Django 5.1.2 on 2025-04-23 19:08

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_alter_book_author_alter_book_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='end_date',
            field=models.DateField(blank=True, validators=[core.validators.check_future, core.validators.check_end_future]),
        ),
    ]
