server {
    listen 80;
    server_name elibrary.businesslaw.school;

    # Redirect HTTP to HTTPS (enable after certbot)
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name elibrary.businesslaw.school;

    # SSL certs (managed by Certbot - paths will be auto-filled)
    ssl_certificate /etc/letsencrypt/live/elibrary.businesslaw.school/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/elibrary.businesslaw.school/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    client_max_body_size 50M;

    location /static/ {
        alias /home/django/NEA_2024_Official-main/blslms/staticfiles/;
    }

    location /media/ {
        alias /home/django/NEA_2024_Official-main/blslms/media/;
    }

    location / {
        include proxy_params;
        proxy_pass http://unix:/run/gunicorn.sock;
    }
}
