"""
Django settings for blslms project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from django.core.exceptions import ImproperlyConfigured


# Jazzmin Admin Theme — BLS Brand
JAZZMIN_SETTINGS = {
    "logout_redirect_url": "/accounts/login",
    "login_redirect_url": "/accounts/login",
    "site_title": "BLS eLibrary Admin",
    "site_header": "BLS eLibrary",
    "site_brand": "BLS eLibrary",
    "site_logo": "logos/favicon.png",
    "login_logo": "logos/BLS-badge.png",
    "login_logo_dark": None,
    "site_logo_classes": "img-circle",
    "site_icon": "logos/favicon.png",
    "welcome_sign": "BLS eLibrary Administration",
    "copyright": "BLS College of Legal Education",
    "user_avatar": None,

    # Top Menu
    "topmenu_links": [
        {"name": "Home", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "Student Site", "url": "/student/dashboard/", "new_window": True},
    ],

    # User Menu
    "usermenu_links": [
        {"name": "BLS Website", "url": "https://businesslaw.school", "new_window": True},
    ],

    # Side Menu
    "show_sidebar": True,
    "navigation_expanded": True,
    "show_recent_actions": False,

    "hide_models": ["core.OnlineBookRead"],

    "order_with_respect_to": [
        "core",
        "core.book",
        "core.physicalbook",
        "core.loan",
        "core.loanissuancenotes",
        "core.damage",
        "core.penalty",
        "core.review",
        "core.reviewnote",
        "core.blsuser",
        "auth",
    ],

    # Icons
    "icons": {
        "auth": "fas fa-shield-alt",
        "auth.Group": "fas fa-users",
        "core": "fas fa-book-open",
        "core.blsuser": "fas fa-user-graduate",
        "core.book": "fas fa-book",
        "core.physicalbook": "fas fa-swatchbook",
        "core.loan": "fas fa-handshake",
        "core.loanissuancenotes": "fas fa-sticky-note",
        "core.damage": "fas fa-exclamation-triangle",
        "core.penalty": "fas fa-gavel",
        "core.review": "fas fa-star",
        "core.reviewnote": "fas fa-clipboard-check",
        "django_celery_beat.periodictask": "fas fa-clock",
        "django_celery_beat.clockedschedule": "fas fa-stopwatch",
        "django_celery_beat.crontabschedule": "fas fa-calendar-alt",
        "django_celery_beat.intervalschedule": "fas fa-hourglass-half",
        "django_celery_beat.solarschedule": "fas fa-sun",
    },
    "default_icon_parents": "fas fa-folder",
    "default_icon_children": "fas fa-circle",

    "related_modal_active": False,

    # Custom CSS
    "custom_css": "css/admin-bls.css",
    "custom_js": None,
    "use_google_fonts_cdn": True,
    "show_ui_builder": False,

    # Change view
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {
        "auth.user": "collapsible",
        "auth.group": "vertical_tabs",
    },
    "language_chooser": False,
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": True,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": False,
    "accent": "accent-primary",
    "navbar": "navbar-dark",
    "no_navbar_border": True,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "default",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success",
    },
}


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.ionos.co.uk'  
EMAIL_PORT = 465
EMAIL_USE_TLS = False  
EMAIL_HOST_USER = os.getenv('NOREPLY_EMAIL')
EMAIL_HOST_PASSWORD = os.getenv('NOREPLY_PWD')
EMAIL_USE_SSL = True
DEFAULT_FROM_EMAIL = os.getenv('NOREPLY_EMAIL')  # Default sender email address
CELERY_BROKER_URL = "redis://localhost:6379/0"
CELERY_RESULT_BACKEND = "redis://localhost:6379/0"
CELERY_ACCEPT_CONTENT = ['json'] #aic
CELERY_TASK_SERIALIZER = 'json'
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY')
if not SECRET_KEY:
    raise ImproperlyConfigured('DJANGO_SECRET_KEY must be set in the environment for deployment.')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DJANGO_DEBUG', 'False').lower() == 'true'
AUTH_USER_MODEL = 'core.BLSUser'
ALLOWED_HOSTS = os.getenv('DJANGO_ALLOWED_HOSTS', 'elibrary.businesslaw.school').split(',')
CSRF_TRUSTED_ORIGINS = ['https://elibrary.businesslaw.school']
STATICFILES_DIRS = [
    BASE_DIR / "static",  # This tells Django to look in the global static folder
]
LOGIN_REDIRECT_URL = '/accounts/login'  # Default redirect after login
ACCOUNT_AUTHENTICATED_LOGIN_REDIRECTS = True  # Default is True
ACCOUNT_LOGOUT_ON_GET = True
ACCOUNT_LOGOUT_REDIRECT_URL = '/accounts/login/'
LOGOUT_REDIRECT_URL = '/accounts/login'

TIME_ZONE = 'UTC'
CELERY_TIMEZONE = 'UTC'

# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'core',
    'django_extensions',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_celery_beat',
]
GRAPH_MODELS = {
    'all_applications': False,
    'apps': ['core'],
    'group_models': True,
}

MIDDLEWARE = [
    'allauth.account.middleware.AccountMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'blslms.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [Path(BASE_DIR / "templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'blslms.wsgi.application'

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
)

SITE_ID = 1
LOGIN_URL = 'account_login'
LOGIN_REDIRECT_URL =  'dashboard'

ACCOUNT_LOGOUT_REDIRECT_URL = '/accounts/login/'

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

CSP_SCRIPT_SRC = ("'self'", "https://acrobatservices.adobe.com")
CSP_DEFAULT_SRC = ("'self'",)

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
X_FRAME_OPTIONS = 'SAMEORIGIN'

# ── Logging ─────────────────────────────────────────────────
LOG_DIR = os.path.join(BASE_DIR, 'logs')
os.makedirs(LOG_DIR, exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{asctime}] {levelname} {name} {module}:{lineno} | {message}',
            'style': '{',
        },
        'simple': {
            'format': '[{asctime}] {levelname} | {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'file_django': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOG_DIR, 'django.log'),
            'maxBytes': 5 * 1024 * 1024,  # 5 MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
        'file_app': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOG_DIR, 'blslms.log'),
            'maxBytes': 5 * 1024 * 1024,
            'backupCount': 5,
            'formatter': 'verbose',
        },
        'file_celery': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOG_DIR, 'celery.log'),
            'maxBytes': 5 * 1024 * 1024,
            'backupCount': 5,
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file_django'],
            'level': 'WARNING',
            'propagate': True,
        },
        'django.request': {
            'handlers': ['console', 'file_django'],
            'level': 'ERROR',
            'propagate': False,
        },
        'blslms': {
            'handlers': ['console', 'file_app'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
        'celery': {
            'handlers': ['console', 'file_celery'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}
# ────────────────────────────────────────────────────────────

#chec